[versions]
idea-ext = "1.4"
nmcp = "1.4.4"
problem4j-spring = "2.1.2"
spotless = "8.2.1"
spring-boot = "4.0.2"
springdoc-openapi = "3.0.1"
testclock = "1.0.4"

[plugins]
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea-ext" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[libraries]
#####################################
# managed by spring-boot-dependencies
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }

spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-aspectj = { module = "org.springframework.boot:spring-boot-starter-aspectj" }
spring-boot-starter-log4j2 = { module = "org.springframework.boot:spring-boot-starter-log4j2" }
spring-boot-starter-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }

spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-aspectj-test = { module = "org.springframework.boot:spring-boot-starter-aspectj-test" }
spring-boot-starter-restclient-test = { module = "org.springframework.boot:spring-boot-starter-restclient-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }

assertj-core = { module = "org.assertj:assertj-core" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jspecify = { module = "org.jspecify:jspecify" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }

#################################
# managed by problem4j-spring-bom
problem4j-spring-bom = { module = "io.github.problem4j:problem4j-spring-bom", version.ref = "problem4j-spring" }
problem4j-spring-webmvc = { module = "io.github.problem4j:problem4j-spring-webmvc" }

##################################
# managed by springdoc-openapi-bom
springdoc-openapi-bom = { module = "org.springdoc:springdoc-openapi-bom", version.ref = "springdoc-openapi" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui" }

########################
# individulal depedences
testclock = { module = "com.mercateo:test-clock", version.ref = "testclock" }